### ISSUE TITLE
`pip install hip-python` doesn't work

### ISSUE THREAD

**Issue by trz42** [ROCmSoftwarePlatform/hip-python#33]
Just tried to follow the documentation at https://rocm.docs.amd.com/projects/hip-python/en/latest/index.html

```bash
# pip install hip-python
ERROR: Could not find a version that satisfies the requirement hip-python (from versions: none)
ERROR: No matching distribution found for hip-python
```

**Comment by domcharrier** [comment]
Hi,

thanks for submitting this issue. The linked PR will clarify how to install prebuilt HIP Python packages in the `README.md`.
So far we have only uploaded manually created packages to Test PyPI 
We still work on our CI/CD to regularly publish on PyPI.
Unfortunately, we had to move the source release ahead, which caused this confusion.

Right now, you find Test PyPI binary packages for `hip-python` and `hip-python-as-cuda`  for ROCm versions 5.6.0 and 5.6.1 and the install instructions on:

https://test.pypi.org/project/hip-python/
https://test.pypi.org/project/hip-python-as-cuda/

The Test PyPI `simple` lists below  you to understand if there exists a binary package for your operating system
(note the `manylinux_2_17_x86_64` tag) and your particular Python installation (note the `-cp3X-cp3X`).

https://test.pypi.org/simple/hip-python/
https://test.pypi.org/simple/hip-python-as-cuda/

More information on the PyPI binary wheel tags:

https://github.com/pypa/manylinux/blob/main/README.rst
